stages:
  run_pipeline:
    cmd: python src/run_pipeline.py --data-path ${dvc.data} --params params.yaml --model-out models/tfidf_lr.joblib
    deps:
      - src/run_pipeline.py
      - src/preprocess.py
      - src/models.py
      - src/evaluate_pickled.py
      - params.yaml
      - ${dvc.data}
    outs:
      - models/tfidf_lr.joblib
      - outputs/latest
